# Generated by Django 4.2.3 on 2023-07-17 08:48

from django.db import migrations
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
