# Generated by Django 4.2.3 on 2023-07-17 10:37

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to=user.models.create_unique_pass
            ),
        ),
    ]
